# Project name
name: endlessos

# The minimum BuildStream version
min-version: 2.0

# Where elements are stored
element-path: elements

# The uri to download built artifacts from for this project
artifacts:
- url: https://bstcache.endlessos.org

source-caches:
- url: https://gbm.gnome.org:11003

fatal-warnings:
- overlaps

(@):
- freedesktop-sdk.bst:include/runtime.yml
- include/aliases.yml
- include/mirrors.yml
- include/shell.yml

# Options to specify for the project, these provide
# command line switches which control the behavior of
# conditional directives in the element.bst files.
#
options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
    - x86_64
  toolbox:
    type: bool
    default: false
    description: mount host resources similar to toolbox
  x86_64_v3:
    type: bool
    description: Enable x86_64-v3 (EXPERIMENTAL)
    default: false

# Some overrides to the default sandbox execution environment
#
environment:
  LC_ALL: en_US.UTF-8

sandbox:
  build-arch: '%{arch}'

# Some overrides to element configuration based on type
#
# Here we can set a project wide options for various build systems,
# e.g. we can add --disable-gtk-doc to every `./configure` line.
elements:
  autotools:
    variables:
      conf-global: >-
        --disable-static
        --disable-Werror
        --host=%{triplet}
        --build=%{triplet}
        --disable-dependency-tracking
      remove-libtool-modules: true
      remove-libtool-libraries: true

  cmake:
    variables:
      cmake-global: >-
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DCMAKE_C_FLAGS_RELWITHDEBINFO="-DNDEBUG"
        -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-DNDEBUG"
      generator: Ninja
      make-install: env DESTDIR="%{install-root}" cmake --install %{build-dir}

  meson:
    variables:
      meson-global: --buildtype=plain --auto-features=enabled --wrap-mode=nodownload

  filter:
    config:
      include-orphans: true

sources:
  git_repo:
    config:
      ref-format: git-describe
  cargo2:
    config:
      url: crates:crates

split-rules:
  devel:
    (>):
    - '%{indep-libdir}/**/include'
    - '%{indep-libdir}/**/include/**'
    - '%{bindir}/*-config'
    - '%{libdir}/cmake'
    - '%{libdir}/cmake/**'
    - '%{datadir}/cmake'
    - '%{datadir}/cmake/**'
    - '%{datadir}/gir-1.0'
    - '%{datadir}/gir-1.0/**'
    - '%{datadir}/vala*/vapi'
    - '%{datadir}/vala*/vapi/**'
    - '%{datadir}/installed-tests'
    - '%{datadir}/installed-tests/**'
    - '%{libexecdir}/installed-tests'
    - '%{libexecdir}/installed-tests/**'
  doc:
    (>):
    - '%{datadir}/gtk-doc/html'
    - '%{datadir}/gtk-doc/html/**'
  source:
  - '%{sourcedir}'
  - '%{sourcedir}/**'
  vm:
  - '%{datadir}/dbus-1/**'

variables:
  branch: '48'
  branch-nice-name: Nightly #Should be %{branch} if not master
  runstatedir: "/run"

  (?):
  - arch == "x86_64":
      go-arch: "amd64"
      systemd-arch: "x86-64"

  (@):
  - include/image-version.yml

plugins:
- origin: junction
  junction: plugins/buildstream-plugins.bst
  elements:
  - autotools
  - meson
  - cmake
  - make
  sources:
  - patch

- origin: junction
  junction: plugins/buildstream-plugins-community.bst
  elements:
  - collect_manifest
  - pyproject
  sources:
  - gen_cargo_lock
  - cargo2
  - git_module
  - git_repo
  - patch_queue
  - zip

- origin: local
  path: plugins
  elements:
  - collect_initial_scripts

junctions:
  # We can declare these junctions as "internal" because we only use them for build dependencies
  # Therefore we know they can't collide with elements in dependant projects.
  internal:
  - plugins/buildstream-plugins.bst
  - plugins/buildstream-plugins-community.bst

aliases:
  savannah: https://git.savannah.gnu.org/git/
