# colord system user.
#
# The gnome-build-meta.bst:core-deps/colord.bst element doesn't define a colord
# sysuser, and my GNOME OS system indeed doesn't have a colord sysuser.
#
# EOS6 does define a colord user so we match that in EOS7.

#Type Name       ID
g     colord     112
u!    colord     106:112
