# Obsolete system users and groups
#
# This config defines system users and groups that have static IDs in Endless OS
# 6, which may own files in /etc or /var of existing Endless OS systems.
#
# These users aren't used in EOS7 and are only defined for backwards compatibility.

#Type Name       ID
g     Debian-gdm 117
u     Debian-gdm 109:117
g     kalite     128
u     kalite     121:128
g     mail       8
u     mail       8:8
g     man        6
u     man        6:6
g     shadow     42
